### ISSUE TITLE
Help Trying to use make authentication

### ISSUE THREAD

**Issue by AresDev** [snaerth/icelandic-movie-api#1]
I'm trying to authenticate to the api doing the Post using Postman to test your API, but I get:
"Cannot POST /authenticate error"

URL:http://api.biomynd.is/authenticate
Data in body: {"username":"___","password":"___"}

Can you tell me please what I'm doing wrong?

Thanks!

**Comment by snaerth** [comment]
Hello and sorry for the late reply. I have been abroad in asia for 2 months now. But I think the error is because your domain is wrong. It should be api.kvikmyndir.is not api.biomynd.is. I am going to fix the docs to night. Sorry for the late answer and the misspelling in the docs. If this dosen't work pleaselet me know

Happy coding

**Comment by AresDev** [comment]
It's working ok now, thanks!
